import type { Dictionary, Stat } from "./types";
import contact from "../../content/settings/contact.json";
import site from "../../content/settings/site-en.json";

export const en: Dictionary = {
  locale: "en",
  meta: {
    title:
      "Unitrans & Uniagent Varna — Ship Agency, Freight Forwarding & Customs in Bulgarian Ports",
    description:
      "Your trusted partner in Bulgarian ports since 1993. Ship agency, freight forwarding, customs brokerage and port operations in Varna, Burgas and all major Bulgarian ports. Duty teams available 365 days a year.",
  },
  nav: {
    links: [
      { href: "/about", label: "About" },
      { href: "/services", label: "Services" },
      { href: "/cargo", label: "Cargo" },
      { href: "/ports", label: "Ports" },
      { href: "/blog", label: "Blog" },
      { href: "/contact", label: "Contact" },
    ],
    cta: "Request support",
    menuOpen: "Menu",
    menuClose: "Close",
    langSwitch: { code: "BG", label: "Български", href: "/bg" },
  },
  hero: {
    // Editable via /admin (content/settings/site-en.json)
    kicker: site.hero.kicker,
    titleLines: site.hero.titleLines,
    sub: site.hero.sub,
    ctaPrimary: site.hero.ctaPrimary,
    ctaSecondary: site.hero.ctaSecondary,
    slides: [
      {
        src: "/images/hero.webp",
        alt: "Bulk carrier on roadstead near the Port of Varna",
        caption: "Port of Varna",
      },
      {
        src: "/images/cta.webp",
        alt: "Panoramic view of a port terminal",
        caption: "Varna West Terminal",
      },
      {
        src: "/images/operations.webp",
        alt: "Container terminal with cranes",
        caption: "Operational control 24/7",
      },
    ],
    stats: site.stats as Stat[],
  },
  marquee: { label: "Trusted by international companies" },
  about: {
    num: "01",
    kicker: "About us",
    statement: "Two specialised companies. One coordinated team.",
    p1: "For more than 30 years, Unitrans Ltd. and Uniagent Varna Ltd. have been supporting international grain traders, ship owners and logistics companies with dependable local expertise across all major Bulgarian commercial ports.",
    p2: "Long-standing industry experience, an organised operational structure and a commitment to efficient execution have made us a trusted partner for some of the world's leading agricultural and industrial companies.",
    glance: [
      "Established in 1993",
      "20 experienced professionals",
      "Nationwide coverage",
      "ISO certified",
    ],
    moreLink: "Our story and team — read more",
    switchHint: "Select a company",
    companies: [
      {
        id: "unitrans",
        name: "Unitrans Ltd.",
        tagline: "The cargo — from door to port.",
        roles: [
          "Freight forwarding",
          "Customs brokerage",
          "Port logistics",
          "Terminal operations",
        ],
      },
      {
        id: "uniagent",
        name: "Uniagent Varna Ltd.",
        tagline: "The vessel — from arrival to departure.",
        roles: [
          "Ship agency",
          "Husbandry services",
          "Ship repairs",
          "Dry-dock coordination",
        ],
      },
    ],
  },
  services: {
    num: "02",
    kicker: "Services",
    title: "Complete port & logistics solutions.",
    sub: "Specialised services covering every stage of the vessel call and cargo movement.",
    hint: "Select a service",
    moreLink: "Full detail on every service",
    items: [
      {
        id: "ship-agency",
        name: "Ship Agency",
        short: "Full agency support for every vessel — from arrival to departure.",
        points: [
          "Arrival and departure formalities",
          "Vessel clearance and documentation",
          "Husbandry services",
          "Crew changes",
          "Spare parts delivery",
          "Bunkering coordination",
          "Ship repair assistance",
          "Dry-dock coordination",
        ],
        image: "/images/services.webp",
        company: "uniagent",
      },
      {
        id: "freight-forwarding",
        name: "Freight Forwarding",
        short: "Import and export logistics, coordinated door to port.",
        points: [
          "Import and export logistics",
          "Port and terminal coordination",
          "Inland transport arrangements",
          "Cargo documentation",
          "Warehousing arrangements",
        ],
        image: "/images/cargo.webp",
        company: "unitrans",
      },
      {
        id: "customs",
        name: "Customs Brokerage",
        short: "Customs formalities — without friction, without delay.",
        points: [
          "Import and export customs clearance",
          "Transit procedures",
          "Temporary storage formalities",
          "Customs declarations",
          "Communication with customs authorities",
        ],
        image: "/images/about.webp",
        company: "unitrans",
      },
      {
        id: "port-operations",
        name: "Port Operations",
        short: "On-the-ground coordination while cargo is moving.",
        points: [
          "Coordination of loading and discharging",
          "Communication with terminals and vessels",
          "Operational monitoring",
          "Daily progress reporting",
          "Coordination between all involved parties",
        ],
        image: "/images/process.webp",
        company: "unitrans",
      },
    ],
  },
  process: {
    num: "03",
    kicker: "How we work",
    title: "One partner throughout the entire port call.",
    sub: "From the initial nomination to the completion of the operation — our teams coordinate the vessel, cargo, documentation and communication between all involved parties.",
    steps: [
      { name: "Nomination", desc: "You appoint us as your local partner." },
      { name: "Planning", desc: "Pre-arrival preparation and documentation." },
      { name: "Arrival", desc: "Port formalities and vessel clearance." },
      { name: "Cargo operations", desc: "Loading or discharging under control." },
      { name: "Daily reporting", desc: "Quantity updates, every single day." },
      { name: "Customs", desc: "Final documentation and clearance." },
      { name: "Departure", desc: "Operations complete. The vessel sails." },
    ],
    note: "One coordinated local partner and a clear flow of information — throughout the entire port call.",
    scrollHint: "Keep scrolling",
  },
  ops: {
    num: "04",
    kicker: "Operations",
    title: "Operational control around the clock.",
    p1: "Shipping does not follow standard working hours. Our duty teams remain available throughout the year — following ongoing operations and responding whenever their involvement is required.",
    p2: "The operations department maintains direct communication with clients, terminals and vessels, follows loading and discharging progress, and reports any relevant development without delay.",
    listTitle: "What clients receive",
    items: [
      "Continuous follow-up of cargo operations",
      "Daily loaded / discharged quantity reports",
      "Timely operational updates",
      "Direct communication with all involved parties",
      "Fast response to changes",
      "Duty coverage 365 days a year",
    ],
    clockLabel: "Local time · Varna",
    clockSub: "The duty team is available",
  },
  cargo: {
    num: "05",
    kicker: "Cargo expertise",
    title: "Grain and bulk cargo. Three decades of expertise.",
    intro:
      "Agricultural commodities are at the core of our operational experience. For more than three decades, we have supported the handling and movement of grain and other bulk cargoes through Bulgarian ports.",
    agriTitle: "Agricultural commodities",
    agri: ["Wheat", "Corn", "Barley", "Sunflower seeds", "Rapeseed", "Vegetable oils"],
    addTitle: "Additional experience",
    add: ["Fertilisers", "Steel products", "Containers", "Project cargo", "Breakbulk cargo"],
    note: "We understand the time-sensitive nature of commodity operations — and the importance of accurate coordination, documentation and cargo progress information.",
    moreLink: "Cargo expertise in detail",
    slides: [
      { src: "/images/hero.webp", caption: "Vessel on roadstead · Varna" },
      { src: "/images/services.webp", caption: "Grain terminal · loading" },
      { src: "/images/process.webp", caption: "Bulk cargo · top view" },
      { src: "/images/cta.webp", caption: "Varna West · panorama" },
    ],
    dragHint: "Drag",
  },
  ports: {
    num: "06",
    kicker: "Nationwide coverage",
    title: "All major Bulgarian ports.",
    sub: "Consistent service quality — sea and river ports, from the Black Sea to the Danube.",
    legendSea: "Black Sea ports",
    legendRiver: "Danube river ports",
    hint: "Select a port on the map",
    hqBadge: "Head office",
    servicesLabel: "On site",
    moreLink: "Port profiles + live vessel map",
    ports: [
      { id: "varna", name: "Varna", type: "sea", desc: "Bulgaria's largest Black Sea port and our head office. Full scope: agency, forwarding, customs and operations.", tags: ["Agency", "Forwarding", "Customs", "Operations"] },
      { id: "burgas", name: "Burgas", type: "sea", desc: "Key port for bulk and breakbulk cargo on the southern Black Sea coast.", tags: ["Agency", "Forwarding", "Customs"] },
      { id: "balchik", name: "Balchik", type: "sea", desc: "Specialised grain port on the northern Black Sea coast.", tags: ["Agency", "Grain cargo"] },
      { id: "ruse", name: "Ruse", type: "river", desc: "Bulgaria's largest Danube port — the gateway to Central Europe.", tags: ["Agency", "Forwarding", "Customs"] },
      { id: "silistra", name: "Silistra", type: "river", desc: "Danube port at the easternmost point of the Bulgarian riverbank.", tags: ["Agency", "Forwarding"] },
      { id: "tutrakan", name: "Tutrakan", type: "river", desc: "Danube port for grain and bulk cargo.", tags: ["Agency", "Grain cargo"] },
      { id: "svishtov", name: "Svishtov", type: "river", desc: "Danube port with regular bulk cargo handling.", tags: ["Agency", "Forwarding"] },
      { id: "oryahovo", name: "Oryahovo", type: "river", desc: "Danube port serving the northwestern region.", tags: ["Agency", "Forwarding"] },
      { id: "lom", name: "Lom", type: "river", desc: "Bulgaria's second largest Danube port.", tags: ["Agency", "Forwarding", "Customs"] },
      { id: "vidin", name: "Vidin", type: "river", desc: "The westernmost Bulgarian Danube port.", tags: ["Agency", "Forwarding"] },
    ],
  },
  clients: {
    num: "07",
    kicker: "Clients & partners",
    title: "Trusted by international companies.",
    sub: "Long-standing relationships built on dependable execution, clear communication and a thorough understanding of local port procedures.",
    logos: [
      { src: "/logos/cargill.png", name: "Cargill" },
      { src: "/logos/adm.png", name: "ADM" },
      { src: "/logos/chs.png", name: "CHS Inc." },
      { src: "/logos/vitagrain.png", name: "Vitagrain BG" },
      { src: "/logos/oliva.png", name: "Oliva AD" },
      { src: "/logos/grainstore.png", name: "Grainstore" },
      { src: "/logos/svepod.png", name: "Svepod" },
      { src: "/logos/fazerles.png", name: "Fazerles AD" },
      { src: "/logos/buildcom.png", name: "Buildcom EOOD" },
      { src: "/logos/va-intertrading.png", name: "VA Intertrading" },
      { src: "/logos/rkl.png", name: "RKL Limited" },
      { src: "/logos/agros.png", name: "Agros Grain Group" },
      { src: "/logos/terrachim.png", name: "Terrachim 97" },
      { src: "/logos/metalcvet.png", name: "Metalcvet" },
      { src: "/logos/viand.png", name: "Viand" },
      { src: "/logos/nova.png", name: "Nova Trade Co." },
      { src: "/logos/sever-export.png", name: "Sever Export" },
    ],
  },
  faq: {
    num: "08",
    kicker: "Questions",
    title: "Frequently asked questions.",
    // Editable via /admin (content/settings/site-en.json)
    items: site.faq,
  },
  contact: {
    num: "09",
    kicker: "Contact",
    title: "Ready to support your next port call.",
    sub: "Tell us about your vessel, cargo or requirement — our team responds quickly.",
    form: {
      name: "Name",
      company: "Company",
      email: "Email",
      phone: "Phone",
      topic: "Subject of enquiry",
      topics: ["Vessel nomination", "Freight forwarding", "Customs brokerage", "Other enquiry"],
      message: "Message",
      submit: "Send enquiry",
      sending: "Sending…",
      success: "Thank you — your enquiry has been sent.",
      successNote: "We will get back to you as soon as possible.",
      error: "Something went wrong. Please write directly to uniagent@unitrans.bg.",
      required: "Required field",
      consent: "By submitting the form you agree to our",
      consentLink: "Privacy Policy",
    },
    info: {
      emailLabel: "Email",
      phoneLabel: "Phone",
      addressLabel: "Address",
      // Editable via /admin (content/settings/contact.json)
      email: contact.email,
      phone: contact.phone,
      phoneHref: contact.phoneHref,
      address: contact.addressEn,
      dutyLabel: "Duty coverage",
      duty: "365 days a year",
    },
  },
  footer: {
    tagline: "Your trusted partner in Bulgarian ports — since 1993.",
    colNav: "Navigation",
    colContact: "Contact",
    colCompanies: "Companies",
    localTime: "Local time · Varna",
    rights: "All rights reserved.",
    designSystem: "Design system",
    legal: {
      privacy: "Privacy",
      cookies: "Cookies",
      terms: "Terms of Use",
    },
  },
};
